### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by rifsxd** [realme-kernel-opensource/realme_C31_C33_C35_narzo50A-Prime-AndroidT-NEW-kernel-source#2]
![image](https://github.com/user-attachments/assets/7cc9404f-8540-4382-9eca-88d55a79b34c)

**Comment by rifsxd** [comment]
also please tell the proper way to build it if im doing it wrong, i used google gki method

**Comment by rifsxd** [comment]
for c35 rmx3511

**Comment by realme-kernel-opensource** [comment]
Dear Customer,
Please compile using the following config, thanks.
arch/arm64/configs/unisoc_fuzz_ums512_defconfig:1645:CONFIG_ZRAM=m

**Comment by rifsxd** [comment]
![Screenshot_20240731-052532](https://github.com/user-attachments/assets/341fd29e-abd0-4361-8865-13c4b12ebe3b)

Still same problem with code please either fix or give a full guide on how to build properly

**Comment by rifsxd** [comment]
![Screenshot_20240731-071419](https://github.com/user-attachments/assets/4f39a5a2-5b58-4f19-9097-5ea631448ec2)
Same error trying to build with clang r416183b with unisoc_fuzz_ums512_defconfig

**Comment by rifsxd** [comment]
There is a lot of code compilation error not just zram hybridswap, how did you guys built the kernel? Please provide full information, thanks

**Comment by realme-kernel-opensource** [comment]
> There is a lot of code compilation error not just zram hybridswap, how did you guys built the kernel? Please provide full information, thanks

Please delete this line from this Makefile and try compiling again.
drivers/block/zram/Makefile
-- obj-$(CONFIG_ZRAM)      += hybridswap/
According to the error information in the screenshot, some of them have duplicate definitions. Please analyze them according to the prompts. Thank.

**Comment by rifsxd** [comment]
I fixed it myself resolving the duplicates but there were more errors on power/supply/charger drivers
And some sprd errors, lets see if these are still causing errors after removing hybridswap

**Comment by rifsxd** [comment]
![Screenshot_20240803-063813](https://github.com/user-attachments/assets/396798ac-dbe4-4c48-89bc-12e768c46538)
This is the other issue

**Comment by rifsxd** [comment]
![Screenshot_20240803-084651](https://github.com/user-attachments/assets/dbeda47c-ee50-4541-959d-da3bbe55e6d2)


Also this

**Comment by rifsxd** [comment]
After fixing that this is the new error 
![Screenshot_20240803-093507](https://github.com/user-attachments/assets/c0f7c630-0cad-4757-a1b2-3f7c11d2a475)
 Which is probably the last to complete the compilation

**Comment by rifsxd** [comment]
I just dont understand why is it so complex to build this specific kernel tree? It's the only linux kernel source which the user has to fix and modify to build stock device kernel, please either fix it or just make a new branch with the fixes for realme c35 rmx3511 which the user don't need to do anything extra

**Comment by rifsxd** [comment]
Now after resolving all these issues the kernel doesn't even boot on the device...

**Comment by rifsxd** [comment]
I don't think ums512 defconfig is the the correct config file for rmx3511 realme c35 which is ums9230_nico

**Comment by rifsxd** [comment]
I request a dedicated kernel source tree just for realme c35 ums9230_nico rmx3511 which will eliminate all the confusions and errors please!

**Comment by rifsxd** [comment]
Bro just provide a working realme rmx3511 c35 kernel code or just you compile the kernel with KernelSU and send me the kernel image

**Comment by rifsxd** [comment]
Made my own defconfig and now all is okay and working
